### ISSUE TITLE
Aircraft info not Displaying

### ISSUE THREAD

**Issue by elgwhoppo** [yfauser/planespotter#8]
Hey all, with the app in the green in the "health tab" running 100% kubernetes, but I'm still getting "Oops, something went terribly wrong, sorry !" when getting into one of the planes. 

Any idea on how to troubleshoot the dependent services here?

**Comment by yfauser** [comment]
It's been a while since I worked with the app ;-) But let me try to help.

The app server is returning an URL taht points to external sources to get the picture of the plane and a number of aircraft details:
https://github.com/yfauser/planespotter/blob/91d28a705291d4c21bd3700d92c3b4d25c809389/app-server/app/main.py#L109
https://github.com/yfauser/planespotter/blob/91d28a705291d4c21bd3700d92c3b4d25c809389/app-server/app/main.py#L94

Now what gets returned to the frontend service (UI) is not the pictures themselves but links to the pictures. The UI itself is trying to retireve the picture:
https://github.com/yfauser/planespotter/blob/91d28a705291d4c21bd3700d92c3b4d25c809389/frontend/app/main.py#L140

You might run into timeouts there, although I recall that I catched all of those ....

Can you post the logs of the frontend and app server (`kubectl logs`)? That should tell us where things go wrong.

**Comment by afewell** [comment]
Hey @yfauser hope you are doing well! we noticed this a couple weeks ago, we think the issue is looks like there is a new requirement on the API to get an api key ... sadly our internal conversation got subjected to needing to follow vmware policy for employees posting updates to open source apps, so right now we are going through an onboarding process so that way vmware people can help with the update ... not sure how long it will take ... if you happen to be able to fix in the meantime would be grateful, otherwise we will fix once we (I mean someone at vmware smarter than me lol) get through the process, and help maintain going forward. Thanks so much for this great app!

**Comment by afewell** [comment]
Here are some logs from Nate ... 

it looks like they now require an API token and it can’t pull the AircraftList.json. Not sure if that is the root cause, but haven’t had time to dig into it.
 
Just wanted to make everyone aware before they tried to demo it.
 
ADSB source code: (If anyone wants to take a stab at fixing it)
https://github.com/yfauser/planespotter/tree/master/adsb-sync
 
Logs:
kubectl logs adsb-sync-5ccd755df-hr2jl
starting polling data ...
Traceback (most recent call last):
  File "./adsb-sync.py", line 148, in <module>
    main()
  File "./adsb-sync.py", line 140, in main
    r_client)
  File "./adsb-sync.py", line 23, in adsb_poll
    icao_list = gen_icao_list(ac_list)
  File "./adsb-sync.py", line 82, in gen_icao_list
    acftdict = json.loads(acft_json)
  File "/usr/local/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by adsb-related-code** [comment]
Greetings,

All Enthusiast non-commercial access requires hosting of a reliable ADS-B receiver sending data to ADSBX.

How to Setup Receiver: https://adsbexchange.com/how-to-feed/

After you setup a feeder, you can send a screenshot of web page below or you can email me the Internet IP of the feeder to verify.  You need a feeder sending data to ADSBx to get an API key.

https://adsbexchange.com/myip/

To repeat,  the process for API key is as follows:

Setup an ADS-B feeder.
Sent me screenshot or IP of feeder.
You will get API key! 

Basic shopping list.

Pi 3B
SDR
Antenna
4GB+ micro SD Card

ADSBx Forum:https://www.adsbexchange.com/forum/threads/working-new-adsbexchange-base-image-v1-0.618988/

ADSBx Discord: https://discord.gg/P6QZ5KA

Cheers,

James
ADSBx
